version: "3.7"
services:
  postgres:
    image: postgres
    restart: always
    container_name: crud_users_api_db
    hostname: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
  server:
    container_name: crud_users_api_server
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /go/src/github.com/Nahbox/crud-users-api
    env_file: .env
    depends_on:
      - postgres
    networks:
      - default
    ports:
      - "8080:8080"
